name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'notificationsapis/**'
      - 'buf.gen.yaml'
      - 'buf.work.yaml'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: catalystsquad/action-semantic-release-general@v1
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          release-config: "@catalystsquad/release-config-npm-no-publish"